# Generated by Django 4.2.7 on 2025-11-22 12:12

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#FF6B6B', help_text='Hex color code for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image_file', models.ImageField(upload_to=photos.models.get_photo_upload_path)),
                ('thumbnail', models.ImageField(blank=True, upload_to='photos/thumbnails/')),
                ('medium', models.ImageField(blank=True, upload_to='photos/medium/')),
                ('large', models.ImageField(blank=True, upload_to='photos/large/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('visibility_start', models.DateTimeField(blank=True, help_text='When photo becomes visible', null=True)),
                ('visibility_end', models.DateTimeField(blank=True, help_text='When photo stops being visible', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position_x', models.FloatField(default=0.0, help_text='X position in 3D space')),
                ('position_y', models.FloatField(default=0.0, help_text='Y position in 3D space')),
                ('position_z', models.FloatField(default=0.0, help_text='Z position in 3D space')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='photos.tag')),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['upload_date'], name='photos_phot_upload__ee55d7_idx'), models.Index(fields=['is_active'], name='photos_phot_is_acti_b563dc_idx'), models.Index(fields=['position_x', 'position_y', 'position_z'], name='photos_phot_positio_60b837_idx')],
            },
        ),
    ]
